### ISSUE TITLE
Apache 2.0 lets anyone fork this repo

### ISSUE THREAD

**Issue by AbhinavMadahar** [Nikolay-Pomytkin/Enflame#3]
I assume you don't want people to use your work, and that's reasonable. However, that's the exact opposite of what the Apache license does.

It's pretty blatant about it as well. If you haven't, read the whole terms of the Apache 2.0 license on their [website](http://www.apache.org/licenses/LICENSE-2.0). If you want a simplified version, here's a [tl;dr](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0))

However, the relevant part is `2. Grant of Copyright License`
> Subject to the terms and conditions of this License, each Contributor hereby grants to You a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable copyright license to **reproduce, prepare Derivative Works of, publicly display, publicly perform, sublicense, and distribute the Work and such Derivative Works in Source or Object form**

Where `You` means `an individual or Legal Entity exercising permissions granted by this License`

If you release your source code to the public, it's almost impossible to stop someone from forking it. Hell, GitHub has a fork button on the top-right for that exact purpose. If you don't want people using your work, make the repo private (GitHub has a student discount for 7 free private repos) or make a private repo on BitBucket.

That said, I really recommend that you embrace open-source software. Chances are that nobody is going to steal your work, and you might not be able to get your name out if you don't work well with unknown developers.

**Comment by Nikolay-Pomytkin** [comment]
@AbhinavMadahar I've signed up for GitHub Education and waiting for them to confirm their request. (Oh and btw its 5 free private repo's). When I was choosing the License, I didn't really spend much time picking anything out so i just picked something that seemed decent for what I needed. I realize that Open Source Software is great, but for this particular project i want to keep it private. Thanks for the feedback though, it's really appreciated.
